=== dsgoficial/modelagens/masterfile_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MasterFile",
  "description": "Arquivo que descreve os dominios e classes de um modelo de banco de dados espaciais",
  "type": "object",
  "definitions": {
    "dominio": {
      "type": "object",
      "description": "Classes dominio armazenam pares code, value de forma a descrever valores utilizados nas classes. Não especificar 'a ser preenchido'",
      "properties": {
        "nome": { "type": "string" },
        "filtro": { "type": "boolean" },
        "valores": { 
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "code": {
                "type": "integer",
                "description": "Código numérico do domínio"
              },
              "value": {
                "type": "string",
                "description": "Texto equivalente ao código numérico"
              },
              "descricao": {
                "type": "string",
                "default": "-",
                "description": "Descrição textual do código do domínio"
              },
              "valor_filtro": {
                "type": "string",
                "description": "Em caso do código pertencer a um grupo especificar o nome do grupo"
              }
            },
            "required": ["code", "value"],
            "additionalProperties": false
          },
          "minItems": 1
        }
      },
      "required": ["nome", "valores"],
      "additionalProperties": false
    },
    "atributo":{
      "type": "object",
      "description": "Atributo de uma classe. Não especificar chave primária e coluna geométrica",
      "properties": {
        "nome": {
          "type": "string",
          "description": "Nome do atributo"
        },
        "tipo": {
          "type": "string",
          "description": "Tipo do atributo no padrão do PostGreSQL"
        },
        "descricao": {
          "type": "string",
          "default": "-",
          "description": "Descrição textual de um atributo"
        },
        "cardinalidade": {
          "type": "string",
          "enum": ["0..1", "1..1", "0..*", "1..*"],
          "description": "Cardinalidade de uso do atributo"
        },
        "mapa_valor": {
          "type": "string",
          "description": "Caso seja um mapa de valor referenciar o nome do domínio"
        },
        "valores": {
          "oneOf": [
            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "code": { 
                    "type": "integer",
                    "description": "Código numérico do domínio"
                  },
                  "primitivas": {
                    "type": "array",
                    "description": "Lista de restrição para geometrias inválidas.",
                    "items": {
                      "type": "string",
                      "enum": ["MultiPoint", "MultiLinestring", "MultiPolygon"]
                    },
                    "minItems": 1,
                    "uniqueItems": true              
                  }
                },
                "required": ["code"],
                "additionalProperties": false
              },
              "minItems": 1
            },
            {
              "type": "array",
              "items": {
                "type": "integer"
              },
              "minItems": 1
            },
            {
              "type": "object",
              "properties": {
                "MultiPoint": {
                  "type": "array",
                  "items": {
                    "type": "integer"
                  },
                  "minItems": 1
                },
                "MultiLinestring": {
                  "type": "array",
                  "items": {
                    "type": "integer"
                  },
                  "minItems": 1
                },
                "MultiPolygon": {
                  "type": "array",
                  "items": {
                    "type": "integer"
                  },
                  "minItems": 1
                }
              },
              "additionalProperties": false
            }
          ]
        },
        "primitivas": {
          "type": "array",
          "description": "Lista de geometrias válidas para utilizar esse atributo.",
          "items": {
            "type": "string",
            "enum": ["MultiPoint", "MultiLinestring", "MultiPolygon"]
          },
          "minItems": 1,
          "uniqueItems": true
        }
      },
      "required": ["nome", "tipo", "cardinalidade"],
      "additionalProperties": false
    },
    "classe": {
      "type": "object",
      "description": "Classe espaciais",
      "properties": {
        "nome": {
          "type": "string",
          "description": "Nome da classe."
        },      
        "categoria": {
          "type": "string",
          "description": "Categoria da classe."
        },
        "descricao": {
          "type": "string",
          "description": "Descrição textual da classe.",
          "default": "-"
        },
        "primitivas": {
          "type": "array",
          "description": "Lista de geometrias válidas para a classe.",
          "items": {
            "type": "string",
            "enum": ["MultiPoint", "MultiLinestring", "MultiPolygon"]
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "atributos": {
          "type": "array",
          "description": "Lista de atributos da classe",
          "items": { "$ref": "#/definitions/atributo" }
        }
      },
      "required": ["nome", "categoria", "primitivas", "atributos"],
      "additionalProperties": false      
    }
  },
  "properties": {
    "modelo": {
      "description": "Nome do modelo de dados",
      "type": "string"
    },
    "comentario": {
      "description": "Comentário sobre o modelo de dados",
      "type": "string"
    },
    "versao": {
      "description": "Versão do modelo, utilizando Semantic Versioning (https://semver.org/)",
      "type": "string"
    },
    "coord_sys": {
      "description": "Código EPSG",
      "type": "integer"
    },
    "a_ser_preenchido": {
      "description": "Indicia se será gerado um valor nos domínios para 'a ser preenchido'",
      "type": "object",
      "properties": {
        "code": { "type": "integer" },
        "value": { "type": "string" }    
      },
      "required": ["code", "value"]
    },
    "schema_dados":{
      "description": "Nome do schema que contém as classes espaciais no banco de dados",
      "type": "string",      
      "default": "edgv"
    },
    "schema_dominios":{
      "description": "Nome do schema que contém os dominios no banco de dados",
      "type": "string",      
      "default": "dominios"
    },
    "fill_factor":{
      "description": "Valor para o fill factor das tabelas criadas no banco de dados",
      "type": "integer", 
      "minimum": 0,
      "maximum": 100,     
      "default": 80
    },
    "nome_geom":{
      "description": "Nome da coluna geométrica no banco de dados",
      "type": "string",      
      "default": "geom"
    },
    "nome_id":{
      "description": "Nome da coluna de chave primária serial no banco de dados",
      "type": "string",      
      "default": "id"
    },
    "atributos_padrao": {
      "type": "array",
      "items": { "$ref": "#/definitions/atributo" },
      "minItems": 1
    },
    "geom_suffix":{
      "description": "Sufixo aplicado as classes espaciais para indicar o tipo de geometria",
      "type": "object",
      "properties": {
        "MultiPoint": {
          "type": "string",      
          "default": "_p"          
        },
        "MultiLinestring": {
          "type": "string",      
          "default": "_l"              
        },
        "MultiPolygon": {
          "type": "string",      
          "default": "_a"              
        }     
      },
      "additionalProperties": false
    },
    "geom_prefix":{
      "description": "Prefixo aplicado as classes espaciais para indicar o tipo de geometria",
      "type": "object",
      "properties": {
        "MultiPoint": {
          "type": "string",      
          "default": "p"          
        },
        "MultiLinestring": {
          "type": "string",      
          "default": "l"              
        },
        "MultiPolygon": {
          "type": "string",      
          "default": "a"              
        }     
      },
      "additionalProperties": false
    },
    "dominios": {
      "type": "array",
      "items": { "$ref": "#/definitions/dominio" }
    },
    "classes": {
      "type": "array",
      "items": { "$ref": "#/definitions/classe" },
      "minItems": 1
    },
    "extension_classes": {
      "type": "array",
      "items": { "$ref": "#/definitions/classe" },
      "minItems": 1
    }
  },
  "additionalProperties": false,
  "required": ["modelo", "versao", "coord_sys", "classes"]
}

=== dsgoficial/modelagens/modelagens_legadas/edgv_213_topo/master_file_213_topo.json
{
  "modelo": "EDGV 2.1.3 Topo",
  "versao": "5.4.1",
  "schema_dados": "edgv",
  "schema_dominios": "dominios",
  "a_ser_preenchido": {
    "code": 999,
    "value": "A SER PREENCHIDO"
  },
  "atributos_padrao": [
    {
      "nome": "tipo_comprovacao",
      "tipo": "smallint",
      "mapa_valor": "tipo_comprovacao",
      "descricao": "-",
      "cardinalidade": "1..1",
      "valores": [
        {
          "code": 1
        },
        {
          "code": 2
        },
        {
          "code": 3
        }
      ]
    },
    {
      "nome": "tipo_insumo",
      "tipo": "smallint",
      "mapa_valor": "tipo_insumo",
      "descricao": "-",
      "cardinalidade": "1..1",
      "valores": [
        {
          "code": 1
        },
        {
          "code": 2
        },
        {
          "code": 3
        },
        {
          "code": 4
        },
        {
          "code": 5
        }
      ]
    },
    {
      "nome": "observacao",
      "tipo": "VARCHAR(255)",
      "descricao": "-",
      "cardinalidade": "0..1"
    },
    {
      "nome": "data_modificacao",
      "tipo": "timestamp with time zone",
      "descricao": "-",
      "cardinalidade": "0..1"
    },
    {
      "nome": "controle_id",
      "tipo": "uuid",
      "descricao": "-",
      "cardinalidade": "0..1"
    },
    {
      "nome": "ultimo_usuario",
      "tipo": "VARCHAR(255)",
      "descricao": "-",
      "cardinalidade": "0..1"
    }
  ],
  "coord_sys": 31982,
  "fill_factor": 80,
  "nome_geom": "geom",
  "nome_id": "id",
  "geom_suffix": {
    "MultiPoint": "_p",
    "MultiLinestring": "_l",
    "MultiPolygon": "_a"
  },
  "dominios": [
    {
      "nome": "tipo_comprovacao",
      "valores": [
        {
          "code": 1,
          "value": "Confirmado em campo",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Não possível de confirmar em campo",
          "descricao": "-"
        },
        {
          "code": 3,
          "value": "Feição não necessita de confirmação",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "tipo_insumo",
      "valores": [
        {
          "code": 1,
          "value": "Fotointerpretado",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Insumo externo",
          "descricao": "-"
        },
        {
          "code": 3,
          "value": "Processo automático",
          "descricao": "-"
        },
        {
          "code": 4,
          "value": "Aquisição em campo",
          "descricao": "-"
        },
        {
          "code": 5,
          "value": "Mapeamento anterior",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "administracao",
      "valores": [
        {
          "code": 0,
          "value": "Desconhecida",
          "descricao": "-"
        },
        {
          "code": 1,
          "value": "Federal",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Estadual",
          "descricao": "-"
        },
        {
          "code": 3,
          "value": "Municipal",
          "descricao": "-"
        },
        {
          "code": 6,
          "value": "Particular",
          "descricao": "-"
        },
        {
          "code": 7,
          "value": "Concessionada",
          "descricao": "-"
        },
        {
          "code": 97,
          "value": "Não aplicável",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "booleano",
      "valores": [
        {
          "code": 1,
          "value": "Sim",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Não",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "booleano_estendido",
      "valores": [
        {
          "code": 0,
          "value": "Desconhecido",
          "descricao": "-"
        },
        {
          "code": 1,
          "value": "Sim",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Não",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "canteiro_divisorio",
      "valores": [
        {
          "code": 1,
          "value": "Sim",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Não",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "finalidade",
      "valores": [
        {
          "code": 0,
          "value": "Desconhecida",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Tratamento",
          "descricao": "-"
        },
        {
          "code": 3,
          "value": "Recalque",
          "descricao": "-"
        },
        {
          "code": 4,
          "value": "Distribuição",
          "descricao": "-"
        },
        {
          "code": 8,
          "value": "Armazenamento",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "forma_extracao",
      "valores": [
        {
          "code": 5,
          "value": "A céu aberto",
          "descricao": "-"
        },
        {
          "code": 6,
          "value": "Subterrânea",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "indice",
      "valores": [
        {
          "code": 1,
          "value": "Mestra",
          "descricao": "Curva múltipla do quíntuplo da equidistância empregada, sendo a primeira, a relativa ao nível de referência, de altitude igual a zero."
        },
        {
          "code": 2,
          "value": "Normal",
          "descricao": "Curva traçada no intervalo das curvas de nível mestras, sendo múltipla da equidistância empregada."
        },
        {
          "code": 3,
          "value": "Auxiliar",
          "descricao": "Curva traçada com o valor adicional de meia equidistância, com o intuito de melhor representar o relevo."
        }
      ]
    },
    {
      "nome": "jurisdicao",
      "valores": [
        {
          "code": 0,
          "value": "Desconhecida",
          "descricao": "-"
        },
        {
          "code": 1,
          "value": "Federal",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Estadual",
          "descricao": "-"
        },
        {
          "code": 3,
          "value": "Municipal",
          "descricao": "-"
        },
        {
          "code": 6,
          "value": "Particular",
          "descricao": "-"
        },
        {
          "code": 97,
          "value": "Não aplicável",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "material_construcao",
      "valores": [
        {
          "code": 0,
          "value": "Desconhecido",
          "descricao": "-"
        },
        {
          "code": 1,
          "value": "Alvenaria",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Concreto",
          "descricao": "-"
        },
        {
          "code": 3,
          "value": "Metal",
          "descricao": "-"
        },
        {
          "code": 4,
          "value": "Rocha",
          "descricao": "-"
        },
        {
          "code": 5,
          "value": "Madeira",
          "descricao": "-"
        },
        {
          "code": 6,
          "value": "Arame",
          "descricao": "-"
        },
        {
          "code": 7,
          "value": "Tela ou alambrado",
          "descricao": "-"
        },
        {
          "code": 8,
          "value": "Cerca viva",
          "descricao": "-"
        },
        {
          "code": 23,
          "value": "Terra",
          "descricao": "-"
        },
        {
          "code": 97,
          "value": "Não aplicável",
          "descricao": "-"
        },
        {
          "code": 98,
          "value": "Outros",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "modal_uso",
      "valores": [
        {
          "code": 4,
          "value": "Rodoviário",
          "descricao": "-"
        },
        {
          "code": 5,
          "value": "Ferroviário",
          "descricao": "-"
        },
        {
          "code": 6,
          "value": "Metroviário",
          "descricao": "-"
        },
        {
          "code": 8,
          "value": "Rodoferroviário",
          "descricao": "-"
        },
        {
          "code": 9,
          "value": "Aeroportuário",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "nr_linhas",
      "valores": [
        {
          "code": 0,
          "value": "Desconhecido",
          "descricao": "-"
        },
        {
          "code": 1,
          "value": "Simples",
          "descricao": "-"
        },
        {
          "code": 2,
          "value": "Dupla",
          "descricao": "-"
        },
        {
          "code": 3,
          "value": "Múltipla",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "posicao_pista",
      "valores": [
        {
          "code": 12,
          "value": "Adjacentes",
          "descricao": "-"
        },
        {
          "code": 13,
          "value": "Superpostas",
          "descricao": "-"
        },
        {
          "code": 97,
          "value": "Não aplicável",
          "descricao": "-"
        }
      ]
    },
    {
      "nome": "posicao_relativa",
      "valores": [
        {
          "code": 2,
          "value": "Superfície",
          "descricao": "-"
        },
        {
          "code": 3,
          "value": "Elevado",
          "descricao": "-"
        },
        {
          "code": 4,
          "value": "Emerso",
          "descricao": "-"
        },
        {
          "code": 5,
          "value": "Submerso",
          "descricao": "-"
        },
        {
          "code": 6,
          "value": "Subterrâneo",
          "descricao": "-"
        },
        {
          "code": 14,
          "value": "Isolada",
          "descricao": "-"
        },
        {
